jenkins:
  systemMessage: "Controlled by Configuration as Code"

tool:
  git:
    installations:
    - home: "git"
      name: "Default"
      
jobs:
  - script: >
        multibranchPipelineJob('configuration-as-code') {
        branchSources {
                git {
                id = 'configuration-as-code'
                remote('https://github.com/josiemundi/jenkins-ci-example')
                }
          }
        }
